name: Lighthouse CI

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types: ["completed"]

jobs:
  lhci:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli

      - name: Run Lighthouse
        run: |
          lhci autorun \
            --collect.url=https://themoutaintune.github.io/manualdolojista/ \
            --upload.target=temporary-public-storage


